import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function exportBioPDF({ bio, lang, data, style, photo }) {
  // Build a hidden off-screen dark A4 sheet (794 × 1123 px at 96dpi)
  const sheet = document.createElement("div");
  sheet.style.position = "fixed";
  sheet.style.left = "-99999px";
  sheet.style.top = "0";
  sheet.style.width = "794px";
  sheet.style.minHeight = "1123px";
  sheet.style.background = "#0A0F1E";
  sheet.style.color = "#F5F0E8";
  sheet.style.fontFamily = '"DM Sans", system-ui, sans-serif';
  sheet.style.padding = "56px 56px 64px";
  sheet.style.boxSizing = "border-box";

  const isUrdu = lang === "urdu";
  const styleLabel = style.charAt(0).toUpperCase() + style.slice(1);
  const langLabel = lang === "urdu" ? "Urdu Script" : lang === "roman" ? "Roman Urdu" : "English";

  const photoBlock = photo
    ? `<div style="width:110px;height:110px;border-radius:50%;overflow:hidden;border:2.5px solid #C9A84C;box-shadow:0 0 25px rgba(201,168,76,0.3);flex-shrink:0;">
         <img src="${photo}" style="width:100%;height:100%;object-fit:cover;display:block;" />
       </div>`
    : "";

  const cornerOrn = (pos) => {
    const transforms = {
      tl: "top:24px;left:24px;",
      tr: "top:24px;right:24px;transform:scaleX(-1);",
      bl: "bottom:24px;left:24px;transform:scaleY(-1);",
      br: "bottom:24px;right:24px;transform:scale(-1,-1);",
    };
    return `<svg style="position:absolute;width:42px;height:42px;color:rgba(201,168,76,0.45);${transforms[pos]}" viewBox="0 0 32 32" fill="none">
      <path d="M2 2 L 14 2 M 2 2 L 2 14" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      <path d="M2 8 Q 8 8 8 2" stroke="currentColor" stroke-width="1" fill="none"/>
      <path d="M2 18 Q 10 18 10 12 Q 10 4 16 4" stroke="currentColor" stroke-width="0.8" fill="none" opacity="0.7"/>
      <circle cx="8" cy="8" r="1.6" fill="currentColor" opacity="0.8"/>
    </svg>`;
  };

  const facts = [
    ["Name", data.name],
    ["Age", data.age ? `${data.age} Years` : ""],
    ["Height", data.height],
    ["City", data.city],
    ["Marital", data.marital],
    ["Degree", data.degree],
    ["Profession", data.profession],
    ["Maslak", data.maslak],
  ].filter(([, v]) => v && v !== "—" && v !== "");

  sheet.innerHTML = `
    <div style="position:relative;border:1.5px solid rgba(201,168,76,0.3);border-radius:24px;padding:48px;min-height:1011px;background:#0F1629;box-shadow:0 24px 80px rgba(0,0,0,0.6);">
      ${cornerOrn("tl")}${cornerOrn("tr")}${cornerOrn("bl")}${cornerOrn("br")}

      <!-- Header section -->
      <div style="display:flex;align-items:center;justify-content:space-between;border-bottom:1.5px solid #C9A84C;padding-bottom:20px;margin-bottom:28px;">
        <div>
          <div style="font-family:'Playfair Display',serif;font-size:36px;font-weight:700;letter-spacing:1px;background:linear-gradient(135deg,#E6C56A,#C9A84C);-webkit-background-clip:text;color:transparent;">RishtaGPT</div>
          <div style="font-family:'Playfair Display',serif;font-style:italic;font-size:13px;color:#8A8FA8;margin-top:4px;">— ${styleLabel} Bio · ${langLabel} —</div>
        </div>
        ${photoBlock}
      </div>

      <!-- Quick Stats Card Grid -->
      ${facts.length ? `
        <div style="display:grid;grid-template-columns:repeat(4, 1fr);gap:12px 16px;background:rgba(255,255,255,0.03);border:1px solid rgba(201,168,76,0.15);border-radius:16px;padding:16px 20px;margin-bottom:28px;">
          ${facts.map(([k, v]) => `
            <div>
              <div style="font-size:9.5px;text-transform:uppercase;letter-spacing:0.12em;color:#8A8FA8;font-weight:600;">${k}</div>
              <div style="font-size:13.5px;color:#F5F0E8;font-weight:500;margin-top:2px;">${v}</div>
            </div>`).join("")}
        </div>
      ` : ""}

      <!-- Main Bio Text -->
      <div style="
        font-family:${isUrdu ? `'Noto Nastaliq Urdu', serif` : `'Playfair Display', serif`};
        font-size:${isUrdu ? '18px' : '15px'};
        line-height:${isUrdu ? '2.3' : '1.8'};
        color:#F5F0E8;
        direction:${isUrdu ? 'rtl' : 'ltr'};
        text-align:${isUrdu ? 'right' : 'left'};
        white-space:pre-wrap;
        margin-top:10px;
        min-height: 480px;
      ">${escapeHTML(bio)}</div>

      <!-- Footer section -->
      <div style="position:absolute;bottom:48px;left:48px;right:48px;display:flex;align-items:center;justify-content:space-between;padding-top:18px;border-top:1.5px solid #C9A84C;">
        <div style="font-family:'Playfair Display',serif;font-style:italic;font-size:11px;color:#8A8FA8;">
          Generated by RishtaGPT.online · ${new Date().toLocaleDateString("en-GB")}
        </div>
        <div style="display:flex;align-items:center;gap:6px;font-size:10px;color:#C9A84C;">
          <span style="width:4px;height:4px;border-radius:50%;background:#C9A84C;"></span>
          <span>Confidential · Family use only</span>
        </div>
      </div>
    </div>
  `;

  document.body.appendChild(sheet);

  try {
    if (document.fonts && document.fonts.ready) await document.fonts.ready;
    await new Promise((r) => setTimeout(r, 300));

    const canvas = await html2canvas(sheet, {
      scale: 3,
      useCORS: true,
      backgroundColor: "#0A0F1E",
      logging: false,
    });

    const imgData = canvas.toDataURL("image/jpeg", 0.95);
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
      compress: true,
    });

    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = pdf.internal.pageSize.getHeight();
    const imgW = pdfW;
    const imgH = (canvas.height * imgW) / canvas.width;

    if (imgH <= pdfH) {
      pdf.addImage(imgData, "JPEG", 0, 0, imgW, imgH, undefined, "FAST");
    } else {
      let y = 0;
      while (y < imgH) {
        pdf.addImage(imgData, "JPEG", 0, -y, imgW, imgH, undefined, "FAST");
        y += pdfH;
        if (y < imgH) pdf.addPage();
      }
    }

    const safeName = (data.name || "RishtaGPT").replace(/[^a-z0-9_-]/gi, "_");
    pdf.save(`${safeName}_Rishta_Bio.pdf`);
  } finally {
    document.body.removeChild(sheet);
  }
}

function escapeHTML(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
